/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import DAO.EventDAO;
import Entity.Event;
import Entity.Event2;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author zEveerY
 */
public class EditEventForm extends javax.swing.JFrame {
    Event2 event = new Event2();
    EventDAO eventDAO = new EventDAO();
    /**
     * Creates new form NewEventForm
     */
    public EditEventForm(Event2 evento) {
        initComponents();
        event = evento;
        carregar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jb_cancel = new javax.swing.JButton();
        jb_save = new javax.swing.JButton();
        jdc_pick = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtf_desc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtf_locate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jcb_service = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editor de Eventos");

        jPanel1.setBackground(new java.awt.Color(53, 57, 65));
        jPanel1.setMinimumSize(new java.awt.Dimension(852, 523));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(144, 184, 248));
        jLabel1.setText("Editor de Evento");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, 31));

        jb_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/stop.png"))); // NOI18N
        jb_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancelActionPerformed(evt);
            }
        });
        jPanel1.add(jb_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 100, 60));

        jb_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/save.png"))); // NOI18N
        jb_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_saveActionPerformed(evt);
            }
        });
        jPanel1.add(jb_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 100, 60));
        jPanel1.add(jdc_pick, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 430, 38));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(144, 184, 248));
        jLabel3.setText("Data :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 77, 30));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(144, 184, 248));
        jLabel2.setText("Descrição : ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 38));

        jtf_desc.setMinimumSize(new java.awt.Dimension(27, 20));
        jtf_desc.setPreferredSize(new java.awt.Dimension(91, 20));
        jPanel1.add(jtf_desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 430, 38));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(144, 184, 248));
        jLabel5.setText("Local :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 38));

        jtf_locate.setMinimumSize(new java.awt.Dimension(27, 20));
        jtf_locate.setPreferredSize(new java.awt.Dimension(91, 20));
        jPanel1.add(jtf_locate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 430, 38));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(144, 184, 248));
        jLabel4.setText("Serviço :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, 38));

        jcb_service.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Limpeza", "Detetização", "Impermeabilização", "Instalação", "Manutenção de Bombas" }));
        jPanel1.add(jcb_service, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 430, 38));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jb_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jb_cancelActionPerformed

    private void jb_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_saveActionPerformed
        try {
            // TODO add your handling code here:
            save();
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(EditEventForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jb_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditEventForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditEventForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditEventForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditEventForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Entity.Event2 evento = new Event2();
                new EditEventForm(evento).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jb_cancel;
    private javax.swing.JButton jb_save;
    private javax.swing.JComboBox jcb_service;
    private com.toedter.calendar.JDateChooser jdc_pick;
    private javax.swing.JTextField jtf_desc;
    private javax.swing.JTextField jtf_locate;
    // End of variables declaration//GEN-END:variables

    private void save() throws SQLException {
        
        //Get Date
        Date dataTeste = jdc_pick.getDate();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        String datr = formato.format(dataTeste);  
        char d1 = datr.charAt(0);
        char d2 = datr.charAt(1);
        char m1 = datr.charAt(3);
        char m2 = datr.charAt(4);
        char y1 = datr.charAt(6);
        char y2 = datr.charAt(7);
        char y3 = datr.charAt(8);
        char y4 = datr.charAt(9);
        String day = ""+d1+""+d2;
        String month = ""+m1+""+m2;
        String year = ""+y1+""+y2+""+y3+""+y4;
        
        event.setDay(Integer.parseInt(day));
        event.setMonth(Integer.parseInt(month));
        event.setYear(Integer.parseInt(year));
        event.setNotes(jtf_desc.getText());
        
        eventDAO.getConnection();
        eventDAO.updateEvent(event);
        
        JOptionPane.showMessageDialog(null, "Evento alterado com sucesso !");
        
    }

    private void carregar() {
        
        jtf_desc.setText(event.getNotes());

        Date date = new Date();
        Calendar calendar = Calendar.getInstance();

        String currentYear = ""+event.getYear();
        String currentMonth = ""+event.getMonth();
        String currentDate= ""+event.getDay();

        calendar.set(Integer.parseInt(currentYear), Integer.parseInt(currentMonth), Integer.parseInt(currentDate));
        date.setTime(calendar.getTimeInMillis());

        jdc_pick.setDate(date);
    }
}
