/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import DAO.ConfiguracaoDAO;
import Entity.ParametrosDb;
import java.awt.event.KeyEvent;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Igor
 */
public class SetupParForm extends javax.swing.JFrame {

    /**
     * Creates new form SetupParForm
     */
    static ParametrosDb par = new ParametrosDb();
    public SetupParForm() {
        initComponents();
        try {
            carregarCampos();
        } catch (IOException ex) {
            Logger.getLogger(SetupParForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_url = new javax.swing.JTextField();
        tf_user = new javax.swing.JTextField();
        tf_senha = new javax.swing.JTextField();
        tf_bd = new javax.swing.JTextField();
        jb_salvar = new javax.swing.JButton();
        jb_voltar = new javax.swing.JButton();
        bg_padraoPequeno = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("URL:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 90, 47, 26);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuário:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 130, 82, 26);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Senha:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 170, 67, 26);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("BD:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 210, 34, 26);

        tf_url.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tf_url.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_urlKeyPressed(evt);
            }
        });
        getContentPane().add(tf_url);
        tf_url.setBounds(160, 90, 200, 30);

        tf_user.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tf_user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_userKeyPressed(evt);
            }
        });
        getContentPane().add(tf_user);
        tf_user.setBounds(190, 130, 170, 30);

        tf_senha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tf_senha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_senhaKeyPressed(evt);
            }
        });
        getContentPane().add(tf_senha);
        tf_senha.setBounds(180, 170, 180, 30);

        tf_bd.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tf_bd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_bdKeyPressed(evt);
            }
        });
        getContentPane().add(tf_bd);
        tf_bd.setBounds(140, 210, 220, 30);

        jb_salvar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jb_salvar.setText("Salvar");
        jb_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_salvarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_salvar);
        jb_salvar.setBounds(210, 330, 81, 29);

        jb_voltar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jb_voltar.setText("Voltar");
        jb_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_voltar);
        jb_voltar.setBounds(330, 330, 79, 29);

        bg_padraoPequeno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/padraoPequena.png"))); // NOI18N
        getContentPane().add(bg_padraoPequeno);
        bg_padraoPequeno.setBounds(0, -60, 500, 540);

        setSize(new java.awt.Dimension(439, 449));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jb_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_voltarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jb_voltarActionPerformed

    private void jb_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_salvarActionPerformed
        // TODO add your handling code here:
        par.setUrl(tf_url.getText());
        par.setUser(tf_user.getText());
        par.setPass(tf_senha.getText());
        par.setDb(tf_bd.getText());
        ConfiguracaoDAO dao = new ConfiguracaoDAO();
        try {
            dao.writeConf(par);
            JOptionPane.showMessageDialog(null, "Parâmetros alterados com sucesso!!");
            dispose();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(SetupParForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Parâmetros alterados com sucesso!!", null, JOptionPane.ERROR_MESSAGE);
            tf_url.grabFocus();
        }
        
    }//GEN-LAST:event_jb_salvarActionPerformed

    private void tf_urlKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_urlKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jb_salvarActionPerformed(null);
        }else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE){
            jb_voltarActionPerformed(null);
        }
    }//GEN-LAST:event_tf_urlKeyPressed

    private void tf_userKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_userKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jb_salvarActionPerformed(null);
        }else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE){
            jb_voltarActionPerformed(null);
        }
    }//GEN-LAST:event_tf_userKeyPressed

    private void tf_senhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_senhaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jb_salvarActionPerformed(null);
        }else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE){
            jb_voltarActionPerformed(null);
        }
    }//GEN-LAST:event_tf_senhaKeyPressed

    private void tf_bdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_bdKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jb_salvarActionPerformed(null);
        }else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE){
            jb_voltarActionPerformed(null);
        }
    }//GEN-LAST:event_tf_bdKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetupParForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetupParForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetupParForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetupParForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetupParForm().setVisible(true);
            }
        });
    }
    
    public void carregarCampos() throws IOException{
        
        ConfiguracaoDAO daop = new ConfiguracaoDAO();
        par = daop.loadConf();
        tf_user.setText(par.getUser());
        tf_senha.setText(par.getPass());
        tf_url.setText(par.getUrl());
        tf_bd.setText(par.getDb());
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_padraoPequeno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jb_salvar;
    private javax.swing.JButton jb_voltar;
    private javax.swing.JTextField tf_bd;
    private javax.swing.JTextField tf_senha;
    private javax.swing.JTextField tf_url;
    private javax.swing.JTextField tf_user;
    // End of variables declaration//GEN-END:variables
}
